[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 3

[[main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories"
  weight = 4

#[[main]]
#  identifier = "series"
#  name = "Series"
#  url = "/series"
#  weight = 5
#
#[[main]]
#  identifier = "about"
#  name = "About"
#  url = "about"
#  weight = 6

